FPS = 25
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
BOX_SIZE = 20
BOARD_WIDTH = 10
BOARD_HEIGHT = 20
BLANK = '.'
POISON = '-'
MOVE_SIDE_WAYS_FREQ = 0.15
MOVE_DOWN_FREQ = 0.1

TEMPLATE_WIDTH = 5
TEMPLATE_HEIGHT = 5

try:
    from .local_settings import *
except ImportError:
    pass

X_MARGIN = int((WINDOW_WIDTH - BOARD_WIDTH * BOX_SIZE) / 2)
TOP_MARGIN = int((WINDOW_HEIGHT - BOARD_HEIGHT * BOX_SIZE) - 5)
